import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { canonicalProjectPath, projectDigest } from "./ownership.js";

const UNIT_MARKER = "# Generated by omp-workflows";

export type HostService = {
  name: string;
  path: string;
  project: string;
};

export function hostService(project: string): HostService {
  const canonicalProject = canonicalProjectPath(project);
  const name = `omp-workflows-${projectDigest(canonicalProject)}.service`;
  const configHome = process.env.XDG_CONFIG_HOME ?? path.join(os.homedir(), ".config");
  return {
    name,
    path: path.join(configHome, "systemd", "user", name),
    project: canonicalProject,
  };
}

export function installHostService(project: string, cliPath = process.argv[1]): HostService {
  requireUserSystemd();
  if (cliPath === undefined) {
    throw new Error("Cannot determine the omp-workflows CLI path");
  }
  const service = hostService(project);
  assertManagedOrAbsent(service);
  const executable = fs.realpathSync(process.execPath);
  const cli = fs.realpathSync(cliPath);
  const content = renderUnit(service, executable, cli);
  fs.mkdirSync(path.dirname(service.path), { recursive: true, mode: 0o700 });
  writeIfChanged(service.path, content);
  systemctl("daemon-reload");
  systemctl("enable", service.name);
  return service;
}

export function startHostService(project: string): HostService {
  const service = requireInstalledService(project);
  systemctl("start", service.name);
  return service;
}

export function stopHostService(project: string): HostService {
  const service = hostService(project);
  requireUserSystemd();
  if (!fs.existsSync(service.path)) return service;
  assertManaged(service);
  systemctl("stop", service.name);
  return service;
}

export function restartHostService(project: string): HostService {
  const service = requireInstalledService(project);
  systemctl("restart", service.name);
  return service;
}

export function uninstallHostService(project: string): HostService {
  const service = hostService(project);
  requireUserSystemd();
  if (!fs.existsSync(service.path)) {
    systemctl("daemon-reload");
    return service;
  }
  assertManaged(service);
  systemctl("disable", "--now", service.name);
  fs.rmSync(service.path);
  systemctl("daemon-reload");
  return service;
}

function requireInstalledService(project: string): HostService {
  const service = hostService(project);
  requireUserSystemd();
  if (!fs.existsSync(service.path)) {
    throw new Error(
      `Workflow host service is not installed for ${service.project}; run host install first`,
    );
  }
  assertManaged(service);
  return service;
}

function assertManagedOrAbsent(service: HostService): void {
  if (fs.existsSync(service.path)) assertManaged(service);
}

function assertManaged(service: HostService): void {
  if (!fs.readFileSync(service.path, "utf8").startsWith(`${UNIT_MARKER}\n`)) {
    throw new Error(`Refusing to modify unmanaged user unit ${service.path}`);
  }
}

function requireUserSystemd(): void {
  if (process.platform !== "linux") {
    throw new Error("The managed workflow host service requires Linux user systemd");
  }
  try {
    systemctl("show-environment");
  } catch (error) {
    const detail = error instanceof Error ? error.message : String(error);
    throw new Error(`User systemd is unavailable: ${detail}`);
  }
}

function systemctl(...args: string[]): string {
  return execFileSync("systemctl", ["--user", ...args], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  }).trim();
}

function renderUnit(service: HostService, executable: string, cli: string): string {
  return `${UNIT_MARKER}
[Unit]
Description=OMP workflow host
StartLimitIntervalSec=60
StartLimitBurst=5

[Service]
Type=simple
WorkingDirectory=${unitQuote(service.project)}
ExecStart=${unitQuote(executable)} ${unitQuote(cli)} host foreground --project ${unitQuote(service.project)}
Restart=on-failure
RestartSec=5s
KillSignal=SIGTERM
TimeoutStopSec=30s
UMask=0077
NoNewPrivileges=true

[Install]
WantedBy=default.target
`;
}

function unitQuote(value: string): string {
  return JSON.stringify(value.replaceAll("%", "%%"));
}

function writeIfChanged(filePath: string, content: string): void {
  try {
    if (fs.readFileSync(filePath, "utf8") === content) {
      fs.chmodSync(filePath, 0o600);
      return;
    }
  } catch (error) {
    if (!(error instanceof Error && "code" in error && error.code === "ENOENT")) throw error;
  }
  const temporary = `${filePath}.${process.pid}.tmp`;
  fs.writeFileSync(temporary, content, { encoding: "utf8", mode: 0o600 });
  fs.renameSync(temporary, filePath);
}
